---

- name: cluster state snapshot transfer user
  community.mysql.mysql_user:
    name: "{{ galera_cluster_settings.wsrep_sst_user }}"
    password: "{{ galera_cluster_settings.wsrep_sst_pass }}"
#    plugin: "unix_socket"
    host: localhost
    priv: '*.*:RELOAD,PROCESS,LOCK TABLES,REPLICATION CLIENT'
    state: present
    login_unix_socket: "{{ mysql_conf_settings.socket }}"
  changed_when: False
  when: not 'rsync' in galera_cluster_settings.wsrep_sst_method and (galera_cluster_settings.wsrep_sst_user is defined)

- name: cluster server configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
    backup: yes
  with_items:
    - "{{ mysql_conf_templates }}"
  notify:
    - stop mysql before bootstrap

- name: Flush handlers
  meta: flush_handlers

- name: cluster bootstrap fix
  file:
    path: /var/log/mysql/mysql.log
    owner: mysql
    group: root
    state: touch
    mode: '0755'
  changed_when: false

- name: cluster master bootstrap
  shell: |
    set -o pipefail
    {{ cluster_bootstrap_cmd }}
  args:
    executable: /bin/bash
    creates: "/var/lib/mysql/grastate.dat"
  become: true
  changed_when: false
  ignore_errors: yes

- name: Cluster - Check node is accepting mysql connections
  wait_for:
    host: "localhost"
    port: "3306"
    delay: 5
    timeout: 300
    state: started
    msg: "Node is now accepting mysql connections"
  connection: local
