---

- name: install mysql packages
  action: >
    {{ ansible_pkg_mgr }} name={{ mysql_package_list }} state=present update_cache=yes
  notify:
    - initialize mysql
    - ensure mysqld dirs exist
    - add custom configuration files
    - fix config in /etc/mysql/mysql.conf.d/mysqld.cnf
    - mysqld bootstrap fix for logging
    - cluster master bootstrap
    - start mysql service

- name: Flush handlers
  meta: flush_handlers

# sst fix after bootstrap TBC
#- name: create cluster sst user
#  shell: |
#    set -o pipefail
#    mysql -ne "{{ item }}"
#  args:
#    executable: /bin/bash
#  with_items:
#    - CREATE USER '{{ wsrep_sst_user }}'@'localhost' IDENTIFIED BY '{{ wsrep_sst_pass }}';
#    - GRANT RELOAD, PROCESS, LOCK TABLES, REPLICATION CLIENT ON *.* TO '{{ wsrep_sst_user }}'@'localhost';
#  changed_when: False
#  when: wsrep_sst_method == 'mariabackup'

- name: Check master node is UP
  wait_for:
    host: "localhost"
    port: "3306"
    delay: 5
    timeout: 300
    state: started
    msg: "Master is not yet UP"
  register: master_is_up
  connection: local
  when: galera_cluster_settings.enabled | bool

# start mysql on slave nodes
