---

- name: Install MySQL packages
  action: >
    {{ ansible_pkg_mgr }} name={{ mysql_package_list }} state=present update_cache=yes
  notify:
    - Initialize mysql instance
    - Required mysql directories exist
    - Standalone instance configuration files
    - Alternate instance configuration files
    - Start mysql service

- name: Flush handlers
  meta: flush_handlers

#- name: Standalone instance configuration files
#  template:
#    src: "{{ item.src }}"
#    dest: "{{ item.dest }}"
#    mode: 0644
#    backup: yes
#  with_items:
#    - "{{ mysql_conf_templates }}"
#  when: not galera_cluster_settings.enabled | bool
#  notify:
#    - Start mysql service

#- name: Alternate instance configuration files
#  template:
#    src: "mysql/server/tmp_server.cnf.j2"
#    dest: "{{ mysql_server_cnf }}"
#    mode: 0644
#  when: galera_cluster_settings.enabled | bool
##  changed_when: false
#  notify:
#    - Start mysql service

#- name: Flush handlers
#  meta: flush_handlers

- name: Check node is accepting mysql connections
  wait_for:
    host: "localhost"
    port: "3306"
    delay: 5
    timeout: 180
    state: started
    msg: "Node is now accepting mysql connections"
  connection: local
  when: galera_cluster_settings.enabled | bool
