---

- name: install mysql packages
  action: >
    {{ ansible_pkg_mgr }} name={{ mysql_package_list }} state=present update_cache=yes
  notify:
    - initialize mysql
    - ensure mysqld dirs exist
    - add custom configuration files
    - fix config in /etc/mysql/mysql.conf.d/mysqld.cnf
    - mysqld bootstrap fix for logging
    - cluster bootstrap
    - start mysql service

- name: Flush handlers
  meta: flush_handlers
