---

- name: install mysql packages
  action: >
    {{ ansible_pkg_mgr }} name={{ mysql_package_list }} state=present update_cache=yes
  notify:
    - initialize mysql
    - ensure mysqld dirs exist
    - add custom configuration files
    - fix config in /etc/mysql/mysql.conf.d/mysqld.cnf
    - mysqld bootstrap fix for logging
    - cluster master bootstrap
    - start mysql service

- name: Flush handlers
  meta: flush_handlers

- name: disable bootstrapping on master node
  lineinfile:
    path: "/var/lib/mysql/grastate.dat"
    regexp: "{{ item }}"
    line: "safe_to_bootstrap: 0"
  with_items:
    - "(safe.*trap.*\\d{1})"
  when: galera_cluster_settings.enabled | bool

#- name: Check master node is UP
#  wait_for:
#    host: "localhost"
#    port: "33069"
#    delay: 5
#    timeout: 300
#    state: started
#    msg: "Master is not yet UP"
#  register: master_is_up
#  connection: local
#  when: galera_cluster_settings.enabled | bool

# start mysql on slave nodes
