---

- name: install mysql packages
  action: >
    {{ ansible_pkg_mgr }} name={{ mysql_package_list }} state=present update_cache=yes
  notify:
    - initialize mysql instance
    - required mysql directories exist
    - standalone instance configuration files
    - temp mysql socket
    - fix config in /etc/mysql/mysql.conf.d/mysqld.cnf
    - start mysql service

- name: Flush handlers
  meta: flush_handlers

- name: Check node is accepting mysql connections
  wait_for:
    host: "localhost"
    port: "3306"
    delay: 5
    timeout: 180
    state: started
    msg: "Node is now accepting mysql connections"
  connection: local
