---

- include: repo-setup.yml

- include: pre-install.yml

- include: install.yml

- include: configure.yml

- include: secure-mysql.yml

- include: galera.yml
  when: (galera_cluster_settings.enabled | bool)
