---

- name: selinux permissive mode for Cluster traffic
  seport:
    ports: "{{ item.port }}"
    proto: "{{ item.port }}"
    setype: mysqld_port_t
    state: present
  with_items:
    - { port: "4567", proto: "tcp" }
    - { port: "4567", proto: "udp" }
    - { port: "4568", proto: "tcp" }
    - { port: "4444", proto: "tcp" }
  when: >
    ansible_selinux is defined and not ansible_selinux | bool and ansible_selinux.status == 'enabled'
    and galera_cluster_settings.enabled | bool

- name: disable SELinux for mysqld
  selinux_permissive:
    name: mysqld_t
    permissive: true
  when: >
    ansible_selinux is defined and not ansible_selinux | bool and ansible_selinux.status == 'enabled'
    and galera_cluster_settings.enabled | bool

- name: apparmor - disabling profile for mysqld
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  register: mysqld_apparmor_disabled
  become: true
  with_items:
    - { src: "/etc/apparmor.d/usr.sbin.mysqld", dest: "/etc/apparmor.d/disable/usr.sbin.mysqld" }
  when: ansible_apparmor.status == 'enabled' and galera_cluster_settings.enabled | bool
  notify:
    - apparmor | reload apparmor profiles

- name: Flush handlers
  meta: flush_handlers

#- name: Install pymysql python module
#  pip:
#    name: pymysql
#    executable: pip3

- name: Install pymysql pip module
  shell: |
    set -o pipefail
    {{ ansible_python.executable }} -m pip install PyMySQL
  args:
    executable: /bin/bash
  changed_when: False
