---

- name: disable SELinux for mysqld
  selinux_permissive:
    name: mysqld_t
    permissive: true
  when: >
    ansible_selinux is defined and not ansible_selinux | bool and ansible_selinux.status == 'enabled'
    and galera_cluster_settings.enabled | bool

- name: apparmor - disabling profile for mysqld
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  register: mysqld_apparmor_disabled
  become: true
  with_items:
    - { src: "/etc/apparmor.d/usr.sbin.mysqld", dest: "/etc/apparmor.d/disable/usr.sbin.mysqld" }
  when: ansible_apparmor.status == 'enabled' and galera_cluster_settings.enabled | bool
  notify:
    - apparmor | reload apparmor profiles

- name: Flush handlers
  meta: flush_handlers
