---

- name: Install basic packages
  action: >
      {{ ansible_pkg_mgr }} name={{ basic_system_packages }} state=present update_cache=yes

- name: Create repository configuration file
  template:
    src: "{{ item.source }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  with_items:
    - "{{ mysql_repo_file_info }}"

- name: Import Debian GPG key
  apt_key:
    keyserver: "{{ item.server }}"
    id: "{{ item.fingerprint }}"
  when: ansible_os_family == 'Debian'
  with_items: "{{ apt_gpg_key_info }}"

- name: Import Redhat GPG key
  shell: |
    set -o pipefail
    curl -fsSL {{ item.url }} -o {{ item.dest }}
    rpm --import {{ item.dest }}
  args:
      executable: /bin/bash
  become: true
  changed_when: false
  when: ansible_os_family == 'RedHat'
  with_items:
    - "{{ rpm_gpg_key_info }}"

- name: Disable mysql mariadb modules
  shell: |
    set -o pipefail
    dnf module disable mysql mariadb -qy
  args:
      executable: /bin/bash
  become: true
  changed_when: false
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version| int >= 8
