---

- name: install basic packages
  action: >
      {{ ansible_pkg_mgr }} name={{ basic_system_packages }} state=present update_cache=yes

- name: create repo file
  template:
    src: "{{ item.source }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  with_items:
    - "{{ mysql_repo_file_info }}"

- name: apt-key - debian gpg key
  apt_key:
    keyserver: "{{ item.server }}"
    id: "{{ item.fingerprint }}"
  when: ansible_os_family == 'Debian'
  with_items: "{{ apt_gpg_key_info }}"

- name: rpm_key - redhat gpg key
  shell: |
    set -o pipefail
    curl -fsSL {{ item.url }} -o {{ item.dest }}
    rpm --import {{ item.dest }}
  args:
      executable: /bin/bash
  become: true
  changed_when: false
  when: ansible_os_family == 'RedHat'
  with_items:
    - "{{ rpm_gpg_key_info }}"

- name: update package cache
  action: >
    {{ ansible_pkg_mgr }} update_cache=yes
