---

- name: install basic packages
  action: >
      {{ ansible_pkg_mgr }} name={{ basic_system_packages }} state=present update_cache=yes

- name: create repo file
  template:
    src: "{{ item.source }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  with_items:
    - "{{ mysql_repo_file_info }}"

- name: apt-key - debian gpg key
  apt_key:
    url: https://mariadb.org/mariadb_release_signing_key.asc
    id: 177F4010FE56CA3336300305F1656F24C74CD1D8
    state: present
  when: ansible_os_family == 'Debian'

- name: rpm_key - redhat gpg key
  rpm_key:
    state: present
    key: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
  when: ansible_os_family == 'RedHat'

- name: update package cache
  action: >
    {{ ansible_pkg_mgr }} update_cache=yes
