---

- name: get mysql tmp socket
  shell: |
    set -o pipefail
    lsof -c mysql | grep "sock.*STRE" | tail -n1 | awk '{print $9}'
  args:
    executable: /bin/bash
  register: mysql_tmp_socket
  changed_when: False

- name: enable mysql general logging
  community.mysql.mysql_query:
    login_unix_socket: "{{ mysql_tmp_socket.stdout }}"
    login_db: mysql
    query:
      - SET GLOBAL general_log_file='/var/log/mysql/queries.log'
      - SET GLOBAL log_output = 'FILE'
      - SET GLOBAL general_log = 1
  changed_when: False

- name: Remove anonymous users
  community.mysql.mysql_query:
    login_unix_socket: "{{ mysql_tmp_socket.stdout }}"
    login_db: mysql
    query:
      - DELETE FROM mysql.user WHERE User=''
  changed_when: False

- name: Disallow root login remotely
  community.mysql.mysql_query:
    login_unix_socket: "{{ mysql_tmp_socket.stdout }}"
    login_db: mysql
    query:
      - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: False

- name: Remove test database and access to it
  community.mysql.mysql_query:
    login_unix_socket: "{{ mysql_tmp_socket.stdout }}"
    login_db: mysql
    query:
      - DROP DATABASE IF EXISTS test
      - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
  changed_when: False

- name: set root password and flush privileges
  community.mysql.mysql_query:
    login_unix_socket: "{{ mysql_tmp_socket.stdout }}"
    login_db: mysql
    query:
      - ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_install_settings.root_password }}'; FLUSH PRIVILEGES;
  changed_when: False
  when: mysql_install_settings.root_password|length > 0

- name: selinux - change mysql port to {{ mysql_conf_settings.port }}
  seport:
    ports: "{{ mysql_conf_settings.port }}"
    proto: tcp
    setype: mysqld_port_t
    state: present
  when: ansible_os_family == 'RedHat' and (mysql_conf_settings.port|int != 3306 and ansible_selinux.status == 'enabled')
