---

- name: Remove anonymous users
  shell: >
    set -o pipefail
    mysql -ne "{{ item }}"
    && echo -n COMPLETED
  args:
    executable: /bin/bash
  with_items:
    - DELETE FROM mysql.user WHERE User=''
  register: remove_anonymous_user
  changed_when: remove_anonymous_user.stdout != 'COMPLETED'
  when: mysql_install_settings.harden_security| bool

- name: Disallow root login remotely
  shell: >
    set -o pipefail
    mysql -ne "{{ item }}"
    && echo -n COMPLETED
  args:
    executable: /bin/bash
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  register: disallow_remote_root
  changed_when: disallow_remote_root.stdout != 'COMPLETED'
  when: mysql_install_settings.harden_security| bool

- name: Remove test database and access to it
  shell: >
    set -o pipefail
    mysql -ne "{{ item }}"
    && echo -n COMPLETED
  args:
    executable: /bin/bash
  with_items:
    - DROP DATABASE IF EXISTS test
    - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
  register: remove_test_database
  changed_when: remove_test_database.stdout != 'COMPLETED'
  when: mysql_install_settings.harden_security| bool

- name: set root password and flush privileges
  shell: >
    set -o pipefail
    mysql -ne "{{ item }}"
    && echo -n COMPLETED
  args:
    executable: /bin/bash
  with_items:
    - ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_install_settings.root_password }}'; FLUSH PRIVILEGES;
  register: set_root_password
  changed_when: set_root_password.stdout != 'COMPLETED'
  when: mysql_install_settings.root_password|length > 0 and mysql_install_settings.harden_security| bool

- name: selinux - Allow mysql to listen on tcp port {{ mysql_conf_settings.port }}
  seport:
    ports: "{{ mysql_conf_settings.port }}"
    proto: tcp
    setype: mysqld_port_t
    state: present
  when: ansible_os_family == 'RedHat' and (mysql_conf_settings.port|int != 3306 and ansible_selinux.status == 'enabled')
