---

- name: set mysql root password
  mysql_user:
    check_implicit_admin: yes
    name: root
    password: "{{ mysql_install_settings.root_password }}"
    host: "{{ item }}"
    state: present
  with_items:
    - localhost
    - 127.0.0.1
    - ::1
  when: mysql_install_settings.root_password|length > 0

- name: Reload privilege tables
  shell: |
    set -o pipefail
    mysql -ne "{{ item }}"
  args:
    executable: /bin/bash
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False

- name: Remove anonymous users
  shell: |
    set -o pipefail
    mysql -ne "{{ item }}"
  args:
    executable: /bin/bash
  with_items:
    - DELETE FROM mysql.user WHERE User=''
  changed_when: False

- name: Disallow root login remotely
  shell: |
    set -o pipefail
    mysql -ne "{{ item }}"
  args:
    executable: /bin/bash
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: False

- name: Remove test database and access to it
  shell: |
    set -o pipefail
    mysql -ne "{{ item }}"
  args:
    executable: /bin/bash
  with_items:
    - DROP DATABASE IF EXISTS test
    - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
  changed_when: False

- name: Reload privilege tables
  shell: |
    set -o pipefail
    mysql -ne "{{ item }}"
  args:
    executable: /bin/bash
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False

#- name: change mysql port
#  lineinfile:
#    path: "/etc/my.cnf.d/server.cnf"
#    regexp: '^port='
#    insertafter: '\[mariadb\]'
#    line: "port={{ mysql_conf_settings.port }}"
#  when: mysql_conf_settings.port|int != 3306

- name: selinux - Allow mysql to listen on tcp port {{ mysql_conf_settings.port }}
  seport:
    ports: "{{ mysql_conf_settings.port }}"
    proto: tcp
    setype: mysqld_port_t
    state: present
  when: ansible_os_family == 'RedHat' and (mysql_conf_settings.port|int != 3306 and ansible_selinux.status == 'enabled')
