---

- name: initialize mysql
  shell: |
    set -o pipefail
    mysqld --initialize-insecure --user=mysql --basedir=/usr --datadir=/var/lib/mysql
  args:
      executable: /bin/bash
  become: true
  changed_when: false
  when: not (mysql_install_settings.use_mariadb | bool) and ansible_os_family == 'RedHat' and mysql_install_settings.version is version('8.0', '>=')

- name: ensure /var/run/mysqld is present
  file:
    path: "/var/run/mysqld"
    owner: mysql
    group: root
    state: directory
    recurse: yes
    mode: '0755'
  changed_when: false
  when: ansible_os_family == 'RedHat'

- name: custom configuration
  template:
    src: "mysql/server/99-mysql-custom.cnf"
    dest: "{{ mysql_conf_dir }}/99-server.cnf"
    mode: 0644

- name: start mysql service
  systemd:
    state: started
    name: "{{ mysql_service_daemon }}"
    enabled: yes
