---

- name: initialize mysql
  shell: |
    set -o pipefail
    mysqld --initialize-insecure --user=mysql --basedir=/usr --datadir=/var/lib/mysql
  args:
      executable: /bin/bash
  become: true
  changed_when: false
  when: not (mysql_install_settings.use_mariadb | bool) and ansible_os_family == 'RedHat' and mysql_install_settings.version is version('8.0', '>=')

- name: ensure mysqld dirs exist
  file:
    path: "{{ item }}"
    owner: mysql
    group: root
    state: directory
    recurse: yes
    mode: '0755'
  changed_when: false
#  when: ansible_os_family == 'RedHat'
  with_items:
    - "{{ mysql_dir_list }}"

- name: add custom configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
    backup: yes
  with_items:
  - { src: "{{ mysql_my_cnf_template }}", dest: "{{ mysql_conf.file_path }}" }
  - { src: "mysql/server/99-server.cnf.j2", dest: "{{ mysql_conf.include_dir }}/99-server.cnf" }

- name: start mysql service
  systemd:
    state: started
    name: "{{ mysql_service_daemon }}"
    enabled: yes
