---
- name: Converge
  hosts: all
  tasks:

    - name: set ansible_python_interpreter
      set_fact:
        ansible_python_interpreter: "/usr/bin/python"
      when: ansible_distribution_release == 'xenial' or (ansible_distribution == 'CentOS' and ansible_distribution_major_version| int <= 7)

    - name: "Include hybridadmin.mysql"
      include_role:
#        name: "hybridadmin.mysql"
        name: "ansible-role-mysql"
